name: prod

x-health: &default-health
  interval: 10s
  timeout: 5s
  retries: 5
  start_period: 30s

services:

  postgres:
    image: postgres:16
    container_name: um_postgres_prod
    restart: unless-stopped
    env_file:
      - .env.prod
    volumes:
      - pg_data_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      <<: *default-health

  rabbitmq:
    image: rabbitmq:3-management
    container_name: um_rabbitmq_prod
    restart: unless-stopped
    env_file:
      - .env.prod
    volumes:
      - rabbitmq_data_prod:/var/lib/rabbitmq
    ports:
      - "15672:15672"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      <<: *default-health

  memcached:
    image: memcached:1.6-alpine
    container_name: um_memcached_prod
    restart: unless-stopped
    command: ["-m", "128"]
    healthcheck:
      test: ["CMD-SHELL", "echo 'version' | nc -w 2 127.0.0.1 11211 >/dev/null 2>&1 || exit 1"]
      <<: *default-health

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.0
    container_name: um_elasticsearch_prod
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data_prod:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -sSf http://127.0.0.1:9200/_cluster/health || exit 1"]
      <<: *default-health

  backend:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.backend.prod
    container_name: um_backend_prod
    restart: unless-stopped
    env_file:
      - .env.prod
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      MANAGEMENT_HEALTH_MAIL_ENABLED: "false"
      SPRING_RABBITMQ_HOST: rabbitmq
      MEMCACHED_HOST: memcached
      ELASTICSEARCH_HOST: elasticsearch
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:8080/actuator/health | grep '\"status\":\"UP\"' || exit 1"]
      <<: *default-health

  nginx:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.frontend.prod
    container_name: um_nginx_prod
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://127.0.0.1/health | grep -q 'OK' || exit 1"]
      <<: *default-health

volumes:
  pg_data_prod:
  rabbitmq_data_prod:
  es_data_prod:
