name: prod
version: "3.9"

x-health: &default-health
  interval: 10s
  timeout: 5s
  retries: 6

services:
  postgres:
    image: postgres:16
    container_name: um_postgres_prod
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      <<: *default-health

  rabbitmq:
    image: rabbitmq:3-management
    container_name: um_rabbitmq_prod
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "15672:15672"   # UI management
    volumes:
      - rabbitmq_data_prod:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD-SHELL","rabbitmq-diagnostics -q ping"]
      <<: *default-health

  memcached:
    image: memcached:1.6-alpine
    container_name: um_memcached_prod
    restart: unless-stopped
    command: ["-m","128"]
    healthcheck:
      test: ["CMD-SHELL","echo 'version' | nc -w 2 127.0.0.1 11211 >/dev/null 2>&1 || exit 1"]
      <<: *default-health

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.0
    container_name: um_elasticsearch_prod
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data_prod:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL","curl -sSf http://127.0.0.1:9200/_cluster/health || exit 1"]
      <<: *default-health

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/Dockerfile.backend.prod
    container_name: um_backend_prod
    restart: unless-stopped
    env_file:
      - .env.prod
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_RABBITMQ_HOST: rabbitmq
