jwt:
  secret: test-secret-very-long-and-secure
  expiration: 3600000

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  tenant:
    header: X-Tenant-ID
    default-tenant: tenant-test

